<?php
// Script to generate SQL file offline
$sqlFile = 'new_tables.sql';
$handle = fopen($sqlFile, 'w');

function writeSQL($handle, $txt)
{
    fwrite($handle, $txt . "\n");
}

writeSQL($handle, "-- Database Schema for Cakes and Cards");
writeSQL($handle, "-- Generated by Agent");
writeSQL($handle, "");

// 1. Tables
$tables = [
    "CREATE TABLE IF NOT EXISTS `cakes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `package_type` enum('luxury','regular','medium') NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `image_url` varchar(255) DEFAULT NULL,
  `category` varchar(50) DEFAULT 'Cakes',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;",

    "CREATE TABLE IF NOT EXISTS `user_cake_selections` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `cake_id` int(11) NOT NULL,
  `selected_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `cake_id` (`cake_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;",

    "CREATE TABLE IF NOT EXISTS `invitation_cards` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `package_type` enum('luxury','regular','medium') NOT NULL,
  `name` varchar(255) NOT NULL,
  `image_url` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;",

    "CREATE TABLE IF NOT EXISTS `user_card_customizations` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `card_template_id` int(11) NOT NULL,
  `bride_name` varchar(255) NOT NULL,
  `groom_name` varchar(255) NOT NULL,
  `wedding_date` date DEFAULT NULL,
  `location` varchar(255) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `card_template_id` (`card_template_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;"
];

foreach ($tables as $t) {
    writeSQL($handle, $t);
    writeSQL($handle, "");
}

// 2. Data Extraction
function extractCakes($filePath, $packageType, $handle)
{
    if (!file_exists($filePath))
        return;
    $html = file_get_contents($filePath);
    $dom = new DOMDocument();
    @$dom->loadHTML($html);
    $xpath = new DOMXPath($dom);
    $sections = $xpath->query("//section[@class='menu-section']");
    foreach ($sections as $section) {
        $header = $xpath->query(".//h2", $section)->item(0);
        $category = 'Cakes';
        if ($header && stripos($header->nodeValue, 'Drink') !== false) {
            $category = 'Drinks';
        }
        $cards = $xpath->query(".//div[@class='dish-card']", $section);
        foreach ($cards as $card) {
            $nameNode = $xpath->query(".//h3", $card)->item(0);
            $descNode = $xpath->query(".//p", $card)->item(0);
            $imgNode = $xpath->query(".//img", $card)->item(0);
            $name = $nameNode ? trim($nameNode->nodeValue) : '';
            $description = $descNode ? trim($descNode->nodeValue) : '';
            $imgUrl = $imgNode ? $imgNode->getAttribute('src') : '';
            if ($name) {
                $sql = sprintf(
                    "INSERT INTO `cakes` (`package_type`, `name`, `description`, `image_url`, `category`) VALUES ('%s', '%s', '%s', '%s', '%s');",
                    $packageType,
                    addslashes($name),
                    addslashes($description),
                    addslashes($imgUrl),
                    addslashes($category)
                );
                writeSQL($handle, $sql);
            }
        }
    }
}

extractCakes('regCake.html', 'regular', $handle);
extractCakes('medCake.html', 'medium', $handle);
extractCakes('LuxCake.php', 'luxury', $handle);

function extractCards($filePath, $packageType, $handle)
{
    if (!file_exists($filePath))
        return;
    $html = file_get_contents($filePath);
    $dom = new DOMDocument();
    @$dom->loadHTML($html);
    $xpath = new DOMXPath($dom);
    $cards = $xpath->query("//div[contains(@class, 'card-option')]");
    foreach ($cards as $card) {
        $nameNode = $xpath->query(".//h3", $card)->item(0);
        $imgNode = $xpath->query(".//img", $card)->item(0);
        $name = $nameNode ? trim($nameNode->nodeValue) : 'Unknown Card';
        $imgUrl = $imgNode ? $imgNode->getAttribute('src') : '';
        if ($imgUrl) {
            $sql = sprintf(
                "INSERT INTO `invitation_cards` (`package_type`, `name`, `image_url`) VALUES ('%s', '%s', '%s');",
                $packageType,
                addslashes($name),
                addslashes($imgUrl)
            );
            writeSQL($handle, $sql);
        }
    }
}

extractCards('invCardLux.html', 'luxury', $handle);
extractCards('invCardMed.html', 'medium', $handle);
extractCards('invCardReg.html', 'regular', $handle);

fclose($handle);
echo "SQL file generated: $sqlFile";
?>